#!/bin/sh

# File to append the message to
COMMIT_MSG_FILE=$1

# Get the committer's name and email
COMMITTER_NAME=$(git config user.name)
COMMITTER_EMAIL=$(git config user.email)

# Construct the message to append
APPEND_MSG="${COMMITTER_NAME} <${COMMITTER_EMAIL}>, on behalf of Mercedes-Benz Tech Innovation GmbH"

# Append the message to the commit message file
echo "$APPEND_MSG" >> "$COMMIT_MSG_FILE"