core:
  production: custom-production
  development: custom-develop
  release: custom-release
  hotfix: custom-hotfix

plugins:
  mvn:
    executor: docker
  npm:
    executor: docker
  python:
    executor: docker
  composer:
    executor: docker

