name: BlackDuck Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  blackduck-scan:
    name: BlackDuck Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: BlackDuck Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        env:
          DETECT_PROJECT_NAME: ${{ github.repository }}
          DETECT_PROJECT_VERSION_LICENSE: MIT License
          DETECT_GO_MOD_DEPENDENCY_TYPES_EXCLUDED: UNUSED
          DETECT_WAIT_FOR_RESULTS: true
          DETECT_POLICY_CHECK_FAIL_ON_SEVERITIES: NONE
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_scan_full:  ${{ github.event_name != 'pull_request' }}

      #- name: Black Duck Full Scan
      #  if: ${{ github.event_name != 'pull_request' }}
      #  uses: synopsys-sig/synopsys-action@v1.13.0
      #  env:
      #    DETECT_PROJECT_NAME: ${{ github.repository }} # change to ${{ github.event.repository.name }}
      #    DETECT_POLICY_CHECK_FAIL_ON_SEVERITIES: ALL
      #    #DETECT_GO_MOD_DEPENDENCY_TYPES_EXCLUDED: UNUSED
      #  with:
      #    blackduck_url: ${{ secrets.BLACKDUCK_URL }}
      #    blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
      #    blackduck_scan_full: true
      #- name: Black Duck PR Scan
      #  if: ${{ github.event_name == 'pull_request' }}
      #  uses: synopsys-sig/synopsys-action@v1.13.0
      #  env:
      #    DETECT_PROJECT_NAME: ${{ github.repository }} # change to ${{ github.event.repository.name }}
      #    #DETECT_GO_MOD_DEPENDENCY_TYPES_EXCLUDED: UNUSED
      #  with:
      #    blackduck_url: ${{ secrets.BLACKDUCK_URL }}
      #    blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
#