name: Blackduck Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  blackduck-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
