name: BlackDuck Scan

on:
  push:
    branches:
      - main
      - feature/blackduck-action
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  blackduck-scan:
    name: BlackDuck Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Black Duck Scan
      #  uses: synopsys-sig/synopsys-action@v1.13.0
      #  env:
      #    DETECT_PROJECT_NAME: ${{ github.repository }}
      #    DETECT_PROJECT_VERSION_NAME: ${{ github.event_name == 'pull_request' && format('PR-{0}', github.event.pull_request.number) || github.ref_name }}
      #  with:
      #    blackduck_url: ${{ secrets.BLACKDUCK_URL }}
      #    blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
      #    blackduck_scan_full:  ${{ github.event_name != 'pull_request' }}
#
      #    ### PULL REQUEST COMMENTS: Uncomment below to enable
      #    #blackduck_prcomment_enabled: true
      #    #github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.13.0
        env:
          DETECT_PROJECT_NAME: ${{ github.repository }} # change to ${{ github.event.repository.name }}
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_scan_full: true
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
      - name: Black Duck PR Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.13.0
        env:
          DETECT_PROJECT_NAME: ${{ github.repository }} # change to ${{ github.event.repository.name }}
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_scan_full: false
          blackduck_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
