name: Blackduck Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  blackduck-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 9.10.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}