name: Black Duck Detect

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  blackduck-scan:
    name: Black Duck Detect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Black Duck Policy
        uses: blackducksoftware/create-policy-action@v0.0.1
        with:
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          policy-name: 'Black Duck Policy For GitHub Actions'
          no-fail-if-policy-exists: true

      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.4
        with:
          scan-mode: INTELLIGENT
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 9.10.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          fail-on-all-policy-severities: true