name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'


      - name: Verify Maven installation
        run: mvn --version

      - name: Install Maven Versions Plugin
        run: |
          mkdir -p ~/.m2/repository/org/codehaus/mojo/versions-maven-plugin
          mvn dependency:get -DgroupId=org.codehaus.mojo -DartifactId=versions-maven-plugin -Dversion=2.16.2

      - name: Test Maven plugin
        run: mvn versions:help

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Application
        run: go build -v ./...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run Tests
        run: |
          gotestsum --format standard-verbose -- -failfast -timeout 60m ./...